# Dataset parameters
dataset_name: 'KITTI' # the name of the dataset. it can be either KITTI or InStereo2K
dataset_path: '.' # for KITTI it's the txt files containing the real path of the images, and for Cityscape it's the path
                  # to the directory that contains leftImg8bit and rightImg8bit folders
resize: [128, 128]

# Model parameters
baseline_model: 'bls17' # can be bmshj18 for Variational image compression with a scale hyperprior by Ballé, et al.
                          # or bls17 for End-to-end Optimized Image Compression by Ballé, et al.
use_side_info: True # if True then the modified version of baseline model for distributed compression is used.
num_filters: 256 # number of filters used in the baseline model network
cuda: True
load_weight: False
weight_path: './pretrained_weights/ours+balle17_MS-SSIM_lambda3e-05.pt' # weight path for loading

# Training parameters
train: False
epochs: 50000
train_batch_size: 12
lr: 0.0001
lambda: 0.00003 # the lambda value in rate-distortion equation
alpha: 1
beta: 1
distortion_loss: 'MSE' # can be MS-SSIM or MSE. selects the method by which the distortion is calculated during training
verbose_period: 50 # this number determines the period (in terms of epoch count) of the console output. non-positive value indicates no verbose

# Saving weights and results parameters
save_weights: True
save_output_path: './outputs' # path where results and weights will be saved
experiment_name: 'bls17_with_side_info_MS-SSIM_lambda:3e-05'

# Test parameters
test: True
save_image: True
