# Dataset parameters
dataset_name: 'KITTI' # the name of the dataset. it can be either KITTI or InStereo2K
dataset_path: '.' # for KITTI it's the txt files containing the real path of the images, and for Cityscape it's the path
                  # to the directory that contains leftImg8bit and rightImg8bit folders
resize: [128, 128]

# Model parameters - SNN Configuration
model_type: 'SNN' # Spiking Neural Network
baseline_model: 'bls17' # Base architecture (adapted to SNN)
use_side_info: True # Use side information for distributed compression
num_filters: 256 # Number of filters in the network
snn_time_steps: 8 # Number of time steps for SNN (increased from 4 for better integration)
snn_neuron_tau: 2.0 # LIF neuron membrane time constant
cuda: True

# Training parameters
train: True
epochs: 10000
train_batch_size: 8
lr: 0.0001
lambda: 0.00003 # the lambda value in rate-distortion equation
alpha: 1
beta: 1
distortion_loss: 'MSE' # can be MS-SSIM or MSE. selects the method by which the distortion is calculated during training
verbose_period: 50 # this number determines the period (in terms of epoch count) of the console output. non-positive value indicates no verbose

# Saving weights and results parameters
save_weights: True
save_output_path: './outputs' # path where results and weights will be saved
experiment_name: 'SNN_KITTI_stereo_MSE_lambda3e-05'

# Test parameters
test: True
save_image: True
